clone:
    depth: full
pipelines:
    branches:
        '{main,development}':
            - step:
                  script:
                      - git push --mirror git@github.com:Atayen/node-satt.git
