image: atayen/atayen:1.0
clone:
    depth: full
pipelines:
    branches:
        DevOps: 
            - step: 
                name:  check Directory 
                script: 
                  - /bin/ls /opt/atlassian/pipelines/agent/build/
            - step:
                name: put file on production 
                script: 
                  - sed -i '74,79 s/^/#/' .env
                  -  sed -i -e '$a'${L1} .env
                  -  sed -i -e '$a'${L2} .env
                  -  sed -i -e '$a'${L3} .env
                  -  sed -i -e '$a'${L4} .env
                  -  sed -i -e '$a'${L5} .env
                  -  sed -i -e '$a'${L6} .env
                  -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "cd /home/oracles/node_satt_2 && pm2 stop 6"
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "cd /home/oracles/node_satt_2 && pm2 stop 5"
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "rm -rf /home/oracles/node_satt_2/build/"
                  -  sshpass -p ${SCP_PASSWORD1} scp -v -pr ../build/ oracles@92.243.9.233:/home/oracles/node_satt_2/ 
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "cd /home/oracles/node_satt_2/build/ && npm install"
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "cd /home/oracles/node_satt_2/ && pm2 start 5"
                  -  sshpass -p ${SCP_PASSWORD1} ssh oracles@92.243.9.233 "cd /home/oracles/node_satt_2/ && pm2 start 6"