image: atayen/atayen:1.0
clone:
    depth: full
pipelines:
    branches:
        DevOps: 
            - step: 
                name:  check Directory 
                script: 
                  - /bin/ls /opt/atlassian/pipelines/agent/build/
            - step:
                name: put file on production 
                script: 
                  -  sed -i '78,83 s/^/#/' .env
                  -  echo "\r" >> .env
                  -  echo ${L1}
                  -  echo "\r" >> .env
                  -  echo ${L2}
                  -  echo "\r" >> .env
                  -  echo ${L3}
                  -  echo "\r" >> .env
                  -  echo ${L4}
                  -  echo "\r" >> .env
                  -  echo ${L5}
                  -  echo "\r" >> .env
                  -  echo ${L6}
                  -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts
                  -  sshpass -p ${SCP_PASSWORD} scp -v -pr ../build/ gdah@92.243.9.233:/home/oracles/DevOps/