image: atayen/atayen:1.0
clone:
    depth: full
pipelines:
    branches:
        DevOps: 
            - step: 
                name:  check Directory 
                script: 
                  - /bin/ls /opt/atlassian/pipelines/agent/build/
            - step:
                name: put file on production 
                script: 
                  - sed -i '72,77 s/^/#/' .env
#                  -  echo "\n" >> .env
#                  -  echo ${L1}
#                  -  echo "\n" >> .env
#                  -  echo ${L2}
#                  -  echo "\n" >> .env
#                  -  echo ${L3}
#                  -  echo "\n" >> .env
#                  -  echo ${L4}
#                  -  echo "\n" >> .env
#                  -  echo ${L5}
#                  -  echo "\n" >> .env
#                  -  echo ${L6}
                  -  sed -i -e '$a' .env
                  -  echo ${L1} >> .env
                  -  sed -i -e '$a' .env
                  -  echo ${L2} >> .env
                  -  sed -i -e '$a' .env
                  -  echo ${L3} >> .env
                  -  sed -i -e '$a' .env
                  -  echo ${L4} >> .env
                  -  sed -i -e '$a' .env
                  -  echo ${L5} >> .env
                  -  sed -i -e '$a' .env
                  -  echo ${L6} >> .env
                  -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts
                  -  sshpass -p ${SCP_PASSWORD} scp -v -pr ../build/ gdah@92.243.9.233:/home/oracles/DevOps/