image: atayen/atayen:1.0
clone:
    depth: full
pipelines:
    branches:
        DevOps: 
            - step: 
                name:  check Directory 
                script: 
                  - /bin/ls /opt/atlassian/pipelines/agent/build/
            - step:
                name: put file on production 
                script: 
                  -  ssh-keyscan -H 92.243.9.233 >> ~/.ssh/known_hosts
                  -  rm -rf .env
                  -  echo ${ENV} >> .env
                  -  sshpass -p ${SCP_PASSWORD} scp -v -pr ../build/ gdah@92.243.9.233:/home/oracles/DevOps/