name: Sync Private Repo to Public Repo

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  push:
    branches:
      - develop
      
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || (github.event.pusher && github.event.pusher.name != 'dependabot[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'refs/heads/develop'
          
      - name: Add public repo as remote
        run: |
          git remote add public https://github.com/SaTT-Wallet/Backend.git
          git fetch public

      - name: Merge changes to public repo
        run: |
          git checkout public/develop
          git merge -m "Merge from private" HEAD
          git push public public/develop
